version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POnTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5
      timeout: 3s

  web:
    build: .
    container_name: blog-nestjs
    restart: always
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    ports: 
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:

